
export const questions = [

  /* Questions:
   https://learninglink.oup.com/access/content/wetherly_otter4e-student-resources/wetherly_otter4e-chapter-8-multiple-choice-questions
   */

  {
    questionText: "Which of the following is not a greenhouse gas?",
    answers: [
      {id: "1", text: "Methane"},
      {id: "2", text: "Hydrogen", correct: true},
      {id: "3", text: "Carbon Dioxide"},
      {id: "4", text: "Nitrous Oxide"}
    ]
  },
  {
    questionText: " Which one of the following is not a 'renewable' energy" +
      " source?",
    answers: [
      {id: "1", text: "Solar"},
      {id: "2", text: "Coal", correct: true},
      {id: "3", text: "Wave"},
      {id: "4", text: "Wind"}
    ]
  },
  {
    questionText: "A 'green transport plan' is:",
    answers: [
      {id: "1", text: "An environmentally acceptable travel plan devised by a local authority for its area"},
      {id: "2", text: "An internationally agreed strategy for reducing the impact of international transport activity on the global environment"},
      {id: "3", text: "A plan devised by a company or organization to reduce the environmental impact of the transport demands generated by itself and its employees", correct: true},
      {id: "4", text: "The Australian government's plan for a sustainable" +
          " transport sector"}
    ]
  },

  {
    questionText: "Focusing on reducing carbon production to reduce carbon" +
      " dioxide emissions is argued to be the wrong variable to focus on because:",
    answers: [
      {
        id: "1",
        text: "It is impossible to achieve"
      },
      {
        id: "2",
        text: "The focus should be on carbon consumption", correct: true
      },
      {
        id: "3",
        text: "It has nothing to do with carbon dioxide emissions"
      },
      {
        id: "4",
        text: "The focus should be on carbon elimination"
      },
    ]
  },

]
